commands:
  create-init: true
  create-model: true
  create-config: true
  create-service: true
  create-interface: true
  create-controller: true
  create-middleware: true
  create-repository: true
  remove-module: true

templates:
  service: "service.tmpl"
  controller: "controller.tmpl"
  model: "model.tmpl"
  interface: "interface.tmpl"
  config: "config.tmpl"
  config-utils: "config-utils.tmpl"
  config-base: "config-base.tmpl"
  config-database: "config-database.tmpl"
  config-server: "config-server.tmpl"
  module: "module.tmpl"
  app: "app.tmpl"
  middleware: "middleware.tmpl"
  repository: "repository.tmpl"
  dockerfile: "dockerfile.tmpl"
  gitignore: "gitignore.tmpl"
  readme: "readme.tmpl"
  route: "route.tmpl"
  env-example: "env-example.tmpl"
  github-workflows: "github-workflows.tmpl"
  test: "test.tmpl"
  migrations: "migrations.tmpl"


generated-file-structure:
      docs: "docs"
      scripts: ".scripts"
      configs: "configs"
      config_utils: "configs/utils"
      tests: "tests"
      docker: "docker"
      src: "src"
      utils: "src/utils"
      enums: "src/enums"
      models: "src/models"
      routes: "src/routes"
      services: "src/services"
      interfaces: "src/interfaces"
      middlewares: "src/middlewares"
      controllers: "src/controllers"
      repositories: "src/repositories"
      github-workflows: ".github/workflows"
      migrations: "migrations"